# Generated by Django 4.2.7 on 2023-11-06 11:31

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(default='hi', max_length=250, validators=[tweets.models.validate_content]),
            preserve_default=False,
        ),
    ]
